baseURL: https://main.d180cq1p10na41.amplifyapp.com/

languageCode: fr-ca
title: Blogue d'Étienne
theme: vanilla-bootstrap-hugo-theme
#googleAnalytics: UA-123456789-1
#relativeURLs: false
#canonifyURLs: false
enableEmoji: true
taxonomies:
  tag: tags

permalinks:
  post: /:filename/
  book: /:filename/


# See https://feathericons.com/
# The value of pre is the icon name
menu:
  nav:
  - name: Accueil
    pre: home
    url: /
    weight: 1
  - name: Articles
    pre: edit
    url: /post/
    weight: 2
  - name: Livres
    pre: book
    url: /book/
    weight: 3
  - name: Mots clés
    pre: tag
    url: /tags/
    weight: 4
#  - name: 'Maintenant'
#    pre: activity
#    url: /now/
#    weight: 5
  - name: 'À propos'
    pre: smile
    url: /about/
    weight: 5

params:
  includeBootstrapJs: false
  showActiveNav: true
  containerMaxWidth: 800px
  dateFormat: Jan 2, 2006
  homeText: Bienvenue sur mon site.
  #footerText: Made with [Hugo](https://gohugo.io/) & [Vanilla](https://github.com/zwbetz-gh/vanilla-bootstrap-hugo-theme)
  hideFooter: true
  katex: true

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2

# deployment:
#   name: "myDeployment"
#   targets:
#     # An arbitrary name for this target.
#     name : "mydeployment"   
#     URL : gs://etiennewebsite 
#   matchers:
#   #  Cache static assets for 1 year.
#     pattern : "^.+\\.(js|css|svg|ttf)$"
#     cacheControl : "max-age=31536000, no-transform, public"
#     gzip : true

#   matchers:
#     pattern : "^.+\\.(png|jpg)$"
#     cacheControl : "max-age=31536000, no-transform, public"
#     gzip : false

#   matchers:
#     pattern : "^.+\\.(html|xml|json)$"
#     gzip : true

